name: Generate JSDocs

on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - main

jobs:
    generate_docs:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Build
          uses: actions/setup-node@v2
        - run: npm ci
        - run: npx jsdoc -c jsdoc.config.json
        - run: git config --global user.name "${{env.CI_COMMIT_AUTHOR}}"
        - run: git config --global user.email "username@users.noreply.github.com"
        - run: git add -A
        - run: git commit -m 'Update JSDoc' || echo 'No changes to commit'
        - run: git push